server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://ced0d159-4118-41be-b6a5-16f7a9a9298b.ciamlogin.com/ced0d159-4118-41be-b6a5-16f7a9a9298b/v2.0
          audiences: 4823b4a7-6749-4cd0-b83c-aa8b4db59d50

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

azure:
  tenant-id: ${AZURE_TENANT_ID}
  client-id: ${AZURE_API_CLIENT_ID}